[2024-01-09T17:21:57.377+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task manual__2024-01-09T17:12:11.160264+00:00 [queued]>
[2024-01-09T17:21:57.389+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task manual__2024-01-09T17:12:11.160264+00:00 [queued]>
[2024-01-09T17:21:57.390+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 3
[2024-01-09T17:21:57.407+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2024-01-09 17:12:11.160264+00:00
[2024-01-09T17:21:57.417+0000] {standard_task_runner.py:60} INFO - Started process 248 to run task
[2024-01-09T17:21:57.423+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'manual__2024-01-09T17:12:11.160264+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcp.py', '--cfg-path', '/tmp/tmp0sx4jpoq']
[2024-01-09T17:21:57.429+0000] {standard_task_runner.py:88} INFO - Job 102: Subtask local_to_gcs_task
[2024-01-09T17:21:57.496+0000] {task_command.py:423} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task manual__2024-01-09T17:12:11.160264+00:00 [running]> on host f5de67cb9685
[2024-01-09T17:21:57.554+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-01-09T17:21:57.603+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='local_to_gcs_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-09T17:12:11.160264+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-09T17:12:11.160264+00:00'
[2024-01-09T17:21:57.718+0000] {ingest_data_gcp_script.py:24} INFO - Starting upload of /opt/***/input_2024-01.parquet to raw/yellow_tripdata_2024_01
[2024-01-09T17:21:57.875+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/ingest_data_gcp_script.py", line 27, in upload_to_gcs
    blob.rewrite(f)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 3777, in rewrite
    headers.update(_get_encryption_headers(source._encryption_key, source=True))
AttributeError: '_io.BufferedReader' object has no attribute '_encryption_key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_data_gcp_script.py", line 31, in upload_to_gcs
    except google.cloud.exception.GoogleCloudError as err:
NameError: name 'google' is not defined
[2024-01-09T17:21:57.889+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20240109T171211, start_date=20240109T172157, end_date=20240109T172157
[2024-01-09T17:21:57.904+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 102 for task local_to_gcs_task (name 'google' is not defined; 248)
[2024-01-09T17:21:57.919+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-09T17:21:57.952+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
